name: Square Inch Anthro
favicon: null
layout_spectrum: 0.75209
typography_spectrum: 0.8834316208958626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d5cb'
    - '#35322d'
    - '#df6965'
    - '#141414'
    - '#8f908a'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
